apiVersion: v1
kind: Service
metadata:
  name: strapi-kinara
  namespace: staging
spec:
  selector:
    app: strapi-kinara
    tenant: strapi-kinara
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: LoadBalancer
